version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: video2doc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:15-alpine
    container_name: video2doc-postgres
    environment:
      POSTGRES_DB: video2doc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  default:
    name: video2doc-network
